### ISSUE TITLE
invalid character 'S' after object key:value pair

### ISSUE THREAD

**Issue by jacky-yanglei** [stackup-wallet/stackup-bundler#130]
![image](https://user-images.githubusercontent.com/17645850/228531168-8d6e0902-842f-496d-b440-f78432b1cbed.png)

**Comment by hazim-j** [comment]
@jacky-yanglei Can you add more context here. Are you self-hosting a bundler? If so what node are you connecting to? And what network are you on? (assuming Polygon based on your Error response?)

**Comment by hazim-j** [comment]
Related to #131
