### ISSUE TITLE
 polygon  with blockpi RPC 

### ISSUE THREAD

**Issue by Love-Coke** [stackup-wallet/stackup-bundler#131]
i had error on polygon  with blockpi RPC 
{"level":"error","bundler_mode":"private","entrypoint":"0x0576a174D229E3cFA37253523E645A78A0C91B57","chain_id":"137","userop_hash":"0xbf613401ca45443bd8ea27c63408d8ca5c2d87d73877619ea0c346566ce4b3b3","error":"invalid character 'S' after object key:value pair","logger":"stackup_bundler/client/eth_sendUserOperation","caller":"/app/pkg/client/client.go:132","time":"2023-03-29T11:37:11Z","message":"eth_sendUserOperation error"}

**Comment by hazim-j** [comment]
I'm not familiar with blockpi RPC, but keep in mind you will need access to a node with `debug_traceCall` with custom JS tracing enabled. Without it the bundler is not able to run simulations.

See: https://docs.stackup.sh/docs/packages/bundler/install#running-the-bundler
