### ISSUE TITLE
Does not support querying transactions that are more than a few days old

### ISSUE THREAD

**Issue by Kylin-nulls** [stackup-wallet/stackup-bundler#140]
Hi,  when I called the `eth_getUserOperationByHash` interface, I found that older transactions could not be found.

I found the following code:
```go
func filterUserOperationEvent(
	eth *ethclient.Client,
	userOpHash string,
	entryPoint common.Address,
) (*entrypoint.EntrypointUserOperationEventIterator, error) {
	ep, err := entrypoint.NewEntrypoint(entryPoint, eth)
	if err != nil {
		return nil, err
	}
	bn, err := eth.BlockNumber(context.Background())
	if err != nil {
		return nil, err
	}
	toBlk := big.NewInt(0).SetUint64(bn)
	startBlk := big.NewInt(0)
	sub10kBlk := big.NewInt(0).Sub(toBlk, big.NewInt(10000))
	if sub10kBlk.Cmp(startBlk) > 0 {
		startBlk = sub10kBlk
	}

	return ep.FilterUserOperationEvent(
		&bind.FilterOpts{Start: startBlk.Uint64()},
		[][32]byte{common.HexToHash(userOpHash)},
		[]common.Address{},
		[]common.Address{},
	)
}
```
This code queries the latest 10,000 blocks, but in actual use, we may need to query older historical transactions. This affects `eth_getUserOperationByHash` and `eth_getUserOperationReceipt`.

I think a possible fix is to always listen to all `UserOperationEvents` of the current entryPoint and store them in the database.

I very much hope this problem can be fixed, thank you.

**Comment by hazim-j** [comment]
A cap on the block range is required in order to not overload the underlying node. If you require querying historical transaction you may need to use an indexed API instead.

For example:
- [Stackup Data APIs](https://docs.stackup.sh/reference/data-api-endpoints)
- [JiffyScan APIs](https://jiffyscan.readme.io/reference/getting-started-1)
