### ISSUE TITLE
make: air: No such file or directory

### ISSUE THREAD

**Issue by emailtovamos** [stackup-wallet/stackup-bundler#143]
I am getting the following error even though I have done the previously mentioned steps:

```
make dev-private-mode
air -c .air.private-mode.toml
make: air: No such file or directory
make: *** [dev-private-mode] Error 1
```

Any idea what else I might be missing?

**Comment by hazim-j** [comment]
If you run the command `which air`, what do you get?

This error means [air](https://github.com/cosmtrek/air) is not installed on your machine. This is a go package that we use for development to get live reloading. If you've done the previous steps, then the most common cause is your GO paths isn't setup correctly to access commands installed with `go install`.

**Comment by komus-Israel** [comment]
in my case, I did 

`go get -u github.com/cosmtrek/air`

after which, I exported my go bin path, `export PATH=$PATH:$(go env GOPATH)/bin`

then `source ~/.profile` in my case. For others it might be `source ~/.bashrc` or `source ~/.zshrc`
