### ISSUE TITLE
entryPoint: Implementation not supported

### ISSUE THREAD

**Issue by siddharthteli12** [stackup-wallet/stackup-bundler#183]
- Deployed entry point contract on Sepolia Testnet. 
- Passed Sepolia Testnet rpc for `ERC4337_BUNDLER_ETH_CLIENT_URL` in `.env` . 
- Started the bundler with `make dev-private-mode`
- Using curl for eth_sendUserOperation post method.
`curl --request POST \
     --url http://localhost:4337 \
     --header 'accept: application/json' \
     --header 'content-type: application/json' \
     --data '
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "eth_sendUserOperation",
  "params": [
    {
      "sender": "0x0000000000000000000000000000000000000000",
      "nonce": "0x0",
      "initCode": "0x",
      "callData": "0x",
      "callGasLimit": "0x0",
      "verificationGasLimit": "0x0",
      "preVerificationGas": "0x0",
      "maxFeePerGas": "0x0",
      "maxPriorityFeePerGas": "0x0",
      "paymasterAndData": "0x",
      "signature": "0x"
    },
    "0x9F28189720ab5Ff29126FBE8f4F50E0bDE2644BE"
  ]
}
'`
- Getting -` {"error":{"code":-32601,"data":"entryPoint: Implementation not supported","message":"entryPoint: Implementation not supported"},"id":1,"jsonrpc":"2.0"}`

**Comment by hazim-j** [comment]
`0x9F28189720ab5Ff29126FBE8f4F50E0bDE2644BE` is not the canonical EntryPoint address. Either use the EntryPoint `0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789` or override the address with [`ERC4337_BUNDLER_SUPPORTED_ENTRY_POINTS` env variable](https://docs.stackup.sh/docs/erc-4337-bundler-configuration#optional).
