### ISSUE TITLE
method "eth_estimateUserOperationGas" is returning "execution reverted"

### ISSUE THREAD

**Issue by Ghadi8** [stackup-wallet/stackup-bundler#184]
When trying to construct a transaction where the amount to be sent is close to the balance of the address (while still accounting for the gas fees), the rpc method "eth_estimateUserOperationGas" is returning "execution reverted". 

Trying to send 0.005 ETH and the balance is 0.01 ETH.

Error message:
'{"error":{"code":-32521,"data":null,"message":"execution reverted"},"id":52,"jsonrpc":"2.0"}'

PS: It works fine if I lower the amount to 0.004 ETH.

**Comment by MR-Hzy** [comment]
This problem is more serious on Polygon, the most exaggerated is that accounts with 15MATIC cannot transfer out 10MATIC.

but if I use paymaster, all the amount of transaction will be successful.

**Comment by hazim-j** [comment]
@Ghadi8 @MR-Hzy thanks for bringing this up. I'll need to look into this more, but it could be an error in the simulation not accounting for value transfers: https://github.com/stackup-wallet/stackup-bundler/blob/main/pkg/gas/estimate.go#L28

It will likely take me a few days to get to this. If you can figure it out before then, I'm happy to review any PRs too!

**Comment by MR-Hzy** [comment]
I send the issues at https://github.com/eth-infinitism/account-abstraction

https://github.com/eth-infinitism/account-abstraction/issues/299

I change the 4337Entrypoint on my personal chain and trance the debug log, got the `gasleft() < callGasLimit + mUserOp.verificationGasLimit + 5000` get true what ever i set the gas, it will got the same gasleft()

**Comment by sc0Vu** [comment]
Is this issue solved?

I found eth-infinitism just use estimateGas for callGasLimit in bundler: https://github.com/eth-infinitism/bundler/blob/633fb4d8298b432a5b0fa0dc48f2265b80c3a5a5/packages/bundler/src/UserOpMethodHandler.ts#L130

And voltaire retrieve callGasLimit in the same way:
https://github.com/candidelabs/voltaire/blob/cce2163e1a2bb9eeb38b290a370d4f045135a525/voltaire_bundler/bundler/execution_endpoint.py#L150

https://github.com/candidelabs/voltaire/blob/cce2163e1a2bb9eeb38b290a370d4f045135a525/voltaire_bundler/user_operation/user_operation_handler.py#L49

Does it need to use eth_estimateGas for callDataGas?

**Comment by MR-Hzy** [comment]
@sc0Vu eth_estimateGas can only be used to calculate the activated CA account. If the CA account has not been activated, the callGasLimit cannot be obtained by calling the excute method of an ADDRESS (because this address is not yet a Contract)

**Comment by sc0Vu** [comment]
@MR-Hzy

Uh, looks like the callGasLimit would break in both js and python bundler (if CA not established yet).
