### ISSUE TITLE
Error when creating a userOp: replacement op must increase maxFeePerGas and MaxPriorityFeePerGas by >= 10%

### ISSUE THREAD

**Issue by shareefhadid** [stackup-wallet/stackup-bundler#190]
What is the cause of the following error?
pending ops: `replacement op must increase maxFeePerGas and MaxPriorityFeePerGas by >= 10%`

We have a stablecoin AA wallet. A user tried to send a few consecutive transfers but was stopped by this error. We obviously don't want to limit users to waiting for a transfer to be sent before they can send another.

**Comment by hazim-j** [comment]
This can happen if theres a gas spike and your userOp suddenly becomes underprices. If this occurs the userOp will stay in the mempool until either gas prices come down or you replace the userOp with 10% higher fees.

However there were a few edge cases around this that has now been fixed in #194.

**Comment by shareefhadid** [comment]
@hazim-j sorry I have been bugging you a lot lately lol. Based on our discussion in discord, my understanding was that by implementing 2D nonces, we can submit new user ops even from a given account, even if one is stuck in the mempool.

Did I understand correctly?
