### ISSUE TITLE
Why is your preVerificationGas calculation method inconsistent with eth-infinitism/bundler's calculation?

### ISSUE THREAD

**Issue by naiba** [stackup-wallet/stackup-bundler#200]
The results are also inconsistent.

**Comment by hazim-j** [comment]
Hi @naiba, we did use the same method as the reference bundler initially but found that it actually results in a loss for the bundler as the UserOperation size increases.

For the rationale on how we calculate it stackup-bundler see: https://www.stackup.sh/blog/an-analysis-of-preverificationgas

**Comment by naiba** [comment]
> 

How do you define losses? What are these losses based on? Server costs? Usage fees for RPCs enabled with the "debug_" namespace?

**Comment by hazim-j** [comment]
Loss is based on wether or not the EntryPoint compensation is less than the transaction fee spent by the bundler. If the bundler spends more in transaction fees than what it gets back from all the userOps in a batch then the bundler has no incentive to submit that batch in the first place.

**Comment by naiba** [comment]
> Loss is based on wether or not the EntryPoint compensation is less than the transaction fee spent by the bundler. If the bundler spends more in transaction fees than what it gets back from all the userOps in a batch then the bundler has no incentive to submit that batch in the first place.

You're talking about something related to gasPrice, right? It's not related to preVerificationGas. The entryPoint compensates based on the consumed gas and the gasPrice configuration in userOperation. As I understand it, the main factor here is to balance gasPrice, and it's not related to the cost of bundler validating userOperation off-chain.

**Comment by hazim-j** [comment]
> The entryPoint compensates based on the consumed gas and the gasPrice configuration in userOperation.
Yes but that's not the entire picture. The consumed gas is the `verificationGasLimit` and `callGasLimit` used to run the verification and execution phase. But there is a lot of overhead outside of these two phases that these limits don't account for which is covered by `preVerificationGas`.

So the EntryPoint compensation is consumed gas plus the preVerificationGas multiplied by the effective gas price.

**Comment by naiba** [comment]
>Yes but that's not the entire picture

Yes, this is a complex issue and I overlooked the cost of submitting data to the chain.
