### ISSUE TITLE
Bundler gets compensated less than transaction fees on BSC Testnet

### ISSUE THREAD

**Issue by Mister-EA** [stackup-wallet/stackup-bundler#203]
I was testing out the Stackup bundler on BSC testnet, by running the example from eth-infinitism's repo:
https://github.com/eth-infinitism/bundler .

What I noticed though is that the bundler gets compensated less than the transaction fees for the bundled transaction:
https://testnet.bscscan.com/tx/0x47e98ba99b7963d0ebbf8b67d732bb5580f1cafb91a5846aaca7227877f4564d

As you can see the transaction fees are 0.00085717 BNB, whereas the bundler gets compensated 0.0001303665 BNB. 

The logs from the bundler did not show any error during the run. I wonder how it is possible that the bundler accepted to serve such a UserOperation if in the end the compensation does not cover the transaction fees?

**Comment by hazim-j** [comment]
Hi @Mister-EA, what version of the bundler are you using? This bug should have been fixed in [v0.6.7](https://github.com/stackup-wallet/stackup-bundler/releases/tag/v0.6.7).

**Comment by Mister-EA** [comment]
Yes, I was based on an older commit where this check was not in place. The problem with the latest version now is that the examples in https://github.com/eth-infinitism/bundler no longer work due to a big divergence in the gas estimates.

**Comment by hazim-j** [comment]
Have a look at this discussion for the rationale behind the difference: https://github.com/stackup-wallet/stackup-bundler/issues/200
