### ISSUE TITLE
eth_call method not found on bundler

### ISSUE THREAD

**Issue by Mister-EA** [stackup-wallet/stackup-bundler#205]
I am trying to run the SimpleAccount ERC-4337 example here:
https://docs.stackup.sh/docs/getting-started

For this I am using the stackup bundler running locally on port 3000. So my config looks like this:
```
{
  "rpcUrl": "http://localhost:3000",
  "signingKey": "0x876d6e83487dc265a65066449b6fce5a1edfddfb0d67b71df8a9306c5324f192",
  "entryPoint": "0x5FF137D4b0FDCD49DcA30c7CF57E578a026d2789",
  "simpleAccountFactory": "0x9406Cc6185a346906296840746125a0E44976454",
  "paymaster": {
    "rpcUrl": "http://localhost:3000",
    "context": {}
  }
}
```

I guess the `rpcUrl` is the url where the bundler and node are running, and I'm only running the bundler on localhost:3000.

Is there a way to run the SimpleAccount example with the bundler and node on separate urls?

**Comment by hazim-j** [comment]
Have a look at the `overrideBundlerRpc` flag: https://docs.stackup.sh/docs/erc-4337-examples#commands

Note that the `rpcUrl` still needs to be pointing to a node.
