### ISSUE TITLE
CallGasLimit may should set some redundancy

### ISSUE THREAD

**Issue by MR-Hzy** [stackup-wallet/stackup-bundler#208]
Sometime use DAPP can not pass `eth_estimateUserOperationGas` with error `out of gas`. It will success by up the call gas limit about 15%.

tx eg: 
out of gas
https://etherscan.io/tx/0x1bd13d3423d025ce06e9dd152198dc1d669b6eec2d23c175bca6da04471f1393

normal
https://etherscan.io/tx/0x34b0d601fe04b196a639580ecd0cc0b96767e2ccf69d752f0fb93dd1e2bc1cdf

**Comment by MR-Hzy** [comment]
of course~~   i'm using [veta finance](https://app.veta.finance/), connect the wallet and supply, after supply and do withdraw, get the error `out of gas`

![image](https://github.com/stackup-wallet/stackup-bundler/assets/62379160/28f78dda-0917-47ae-808d-a49d38df4153)

it can run normal by metamask

**Comment by hazim-j** [comment]
Hi @MR-Hzy, are you still experiencing this in the latest bundler version?

**Comment by MR-Hzy** [comment]
Looks like it's been fixed, thanks
